#!/bin/sh

#LAUNCHERS
xsetroot -cursor_name left_ptr &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
picom & 
nitrogen --restore &
$HOME/.config/polybar/launch.sh --docky &
openrazer-daemoon -Fv
xfce4-power-manager &
steam &

# here you set desktop names
bspc monitor -d 1 2 3 4 5 6 7 8

# borders and gaps
bspc config border_width         0
bspc config window_gap           30
bspc config top_padding 20

# useful things
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_follows_pointer true


# application rules
bspc rule -a Steam desktop='^5'
bspc rule -a Spotify desktop='^4'
bspc rule -a Xfce4-terminal state=floating follow=on

